In [10]:
import numpy as np
import pandas as pd

fidHB = pd.read_csv('epsilon.csv')
fidcol = pd.read_csv('collagen_mua.csv')
fidwater = pd.read_csv('water_mua.csv')
fidepi = pd.read_csv('mu_epi.csv')
fidmel = pd.read_csv('mel.csv')

In [11]:
fidHB
fidcol
fidwater
fidepi
fidmel

wl     mel
0     250.0  7680.0
1     252.0  7470.0
2     254.0  7270.0
3     256.0  7080.0
4     258.0  6890.0
..      ...     ...
371   992.0    63.5
372   994.0    63.0
373   996.0    62.6
374   998.0    62.2
375  1000.0    61.7

[376 rows x 2 columns]

In [5]:
wl = [i for i in range(700, 900)]
wl

[700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866

In [12]:
mel = np.interp(wl, fidmel['wl'], fidmel['mel'])
mel

array([214.  , 212.5 , 211.  , 210.  , 209.  , 208.  , 207.  , 206.  ,
       205.  , 204.  , 203.  , 202.  , 201.  , 200.  , 199.  , 198.  ,
       197.  , 196.  , 195.  , 194.5 , 194.  , 193.  , 192.  , 191.  ,
       190.  , 189.  , 188.  , 187.  , 186.  , 185.5 , 185.  , 184.  ,
       183.  , 182.  , 181.  , 180.  , 179.  , 178.5 , 178.  , 177.  ,
       176.  , 175.  , 174.  , 173.5 , 173.  , 172.  , 171.  , 170.5 ,
       170.  , 169.  , 168.  , 167.  , 166.  , 165.5 , 165.  , 164.  ,
       163.  , 162.5 , 162.  , 161.  , 160.  , 159.5 , 159.  , 158.5 ,
       158.  , 157.  , 156.  , 155.5 , 155.  , 154.  , 153.  , 152.5 ,
       152.  , 151.5 , 151.  , 150.  , 149.  , 148.5 , 148.  , 147.5 ,
       147.  , 146.  , 145.  , 144.5 , 144.  , 143.5 , 143.  , 142.  ,
       141.  , 140.5 , 140.  , 139.5 , 139.  , 138.5 , 138.  , 137.5 ,
       137.  , 136.  , 135.  , 134.5 , 134.  , 133.5 , 133.  , 132.5 ,
       132.  , 131.5 , 131.  , 130.5 , 130.  , 129.5 , 129.  , 128.  ,
      

In [13]:
dfmel = pd.DataFrame({'wl':wl, 'mel':mel})
dfmel
dfmel.to_csv('dfmel.csv')

In [6]:
epi = np.interp(wl, fidepi['wl'], fidepi['epi'])
epi

array([2.48968974, 2.49210957, 2.4945294 , 2.49226074, 2.48780813,
       2.48335552, 2.47890291, 2.4744503 , 2.46999769, 2.46554508,
       2.46109247, 2.45663985, 2.45218724, 2.44773463, 2.44328202,
       2.43882941, 2.4343768 , 2.42992419, 2.42547158, 2.42101897,
       2.41656635, 2.41211374, 2.4073517 , 2.39590123, 2.38445075,
       2.37300028, 2.3615498 , 2.35009933, 2.33864885, 2.32719837,
       2.3157479 , 2.30429742, 2.29284695, 2.28139647, 2.269946  ,
       2.25849552, 2.24704505, 2.23559457, 2.22414409, 2.21273191,
       2.202537  , 2.19234209, 2.18214718, 2.17195226, 2.16175735,
       2.15156244, 2.14136752, 2.13117261, 2.1209777 , 2.11078278,
       2.10058787, 2.09039296, 2.08019805, 2.07000313, 2.05980822,
       2.04961331, 2.03941839, 2.02922348, 2.01902857, 2.00883366,
       1.99863874, 1.98844383, 1.97824892, 1.968054  , 1.95785909,
       1.94867305, 1.94155408, 1.93443512, 1.92731615, 1.92019718,
       1.91307821, 1.90595924, 1.89884028, 1.89172131, 1.88460

In [7]:
dfepi = pd.DataFrame({'wl':wl, 'epi':epi})
dfepi
dfepi.to_csv('dfepi.csv')

In [ ]:
hb = np.interp(wl, fidHB['wl'], fidHB['hb'])
hb

In [ ]:
hbo2 = np.interp(wl, fidHB['wl'], fidHB['hbo2'])
hbo2

In [ ]:
dfhb = pd.DataFrame({'wl':wl, 'hbo2':hbo2, 'hb':hb})
dfhb
dfhb.to_csv('dfhb.csv')

In [ ]:
col = np.interp(wl, fidcol['wl'], fidcol['col'])
col

In [ ]:
dfcol = pd.DataFrame({'wl':wl, 'col':col})
dfcol
dfcol.to_csv('dfcol.csv')

In [ ]:
water = np.interp(wl, fidwater['wl'], fidwater['water'])
water

array([0.00656667, 0.00673333, 0.0069    , 0.00714167, 0.00738333,
       0.007625  , 0.00786667, 0.00810833, 0.00835   , 0.00859167,
       0.00883333, 0.009075  , 0.00931667, 0.00955833, 0.0098    ,
       0.01012727, 0.01045455, 0.01078182, 0.01110909, 0.01143636,
       0.01176364, 0.01209091, 0.01241818, 0.01274545, 0.01307273,
       0.0134    , 0.01444   , 0.01548   , 0.01652   , 0.01756   ,
       0.0186    , 0.01964   , 0.02068   , 0.02172   , 0.02276   ,
       0.0238    , 0.02413636, 0.02447273, 0.02480909, 0.02514545,
       0.02548182, 0.02581818, 0.02615455, 0.02649091, 0.02682727,
       0.02716364, 0.0275    , 0.0276    , 0.0277    , 0.0278    ,
       0.0279    , 0.028     , 0.0281    , 0.02795   , 0.0278    ,
       0.02765   , 0.0275    , 0.02735   , 0.0272    , 0.02700909,
       0.02681818, 0.02662727, 0.02643636, 0.02624545, 0.02605455,
       0.02586364, 0.02567273, 0.02548182, 0.02529091, 0.0251    ,
       0.024925  , 0.02475   , 0.024575  , 0.0244    , 0.02422

In [ ]:
dfwater = pd.DataFrame({'wl':wl, 'water':water})
dfwater
dfwater.to_csv('dfwater.csv')